old_sound_rabbit_mq:
    connections:
        default:
            url: '%env(RABBITMQ_URL)%'
    producers:
        #...
        mails_queue:
            connection:       default
            exchange_options: {name: 'mails_queue', type: direct}
    consumers:
        #...
        mails_queue: &consumer_mails_queue
            connection:       default
            exchange_options: {name: 'mails_queue', type: direct}
            queue_options:    {name: 'mails_queue'}
            callback:         app.consumer.mails_queue
#    producers:
#        # use 'old_sound_rabbit_mq.task_producer' service to send data.
#        task:
#            connection:       default
#            exchange_options: { name: 'task', type: direct }
#    consumers:
#        task:
#            connection:       default
#            exchange_options: { name: 'task', type: direct }
#            queue_options:    { name: 'task'}
#            callback:         App\Consumer\TaskConsumer
